### ISSUE TITLE
using tmux?

### ISSUE THREAD

**Issue by ankitvad** [giraj/solarized-crosh#3]
Hey, in reference to,

> > > If you are running ChromeOS, have a minimal chroot installed (no X), are working with it using mostly tmux/screen + editor of choice + other terminal tools.

How would one use tmux ? entering chroot in crosh, opens up the debian CLI in crosh only, there is no way to split screens, add stuff etc. AM i missing something ?

**Comment by jarlg** [comment]
You enter chroot (in crosh, using `sudo enter-chroot`) and then open tmux. What's the problem?

**Comment by ankitvad** [comment]
Ahh, i was trying to fix my open ssh secure-shell issue. Also, my tmux commands are all unresponsive. ctrl+b and enything didnt work.. i might have to create a manual tmux.config that takes care of the issue. Thanks. i got it :)
